# This workflow will test the guide application.
# For more information about building and testing Java,
# see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test application

on:
  pull_request:
    branches: [ qa ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 8 ]
    env:
      CHANGE_MINIKUBE_NONE_USER: true
    defaults:
      run:
        working-directory: finish

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - run: unset _JAVA_OPTIONS
    - name: Run tests
      run: |
        sudo ../scripts/startMinikube.sh
        sudo ../scripts/testApp.sh
    - name: Post tests
      if: always()
      run: docker images
